version: '3.8'

services:
  db:
    image: mariadb:10.9
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-redmine_root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-redmine}
      MYSQL_USER: ${MYSQL_USER:-redmine}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-redmine}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redmine:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: ${RAILS_ENV:-production}
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PORT: ${REDMINE_DB_PORT:-3306}
      REDMINE_DB_DATABASE: ${MYSQL_DATABASE:-redmine}
      REDMINE_DB_USERNAME: ${MYSQL_USER:-redmine}
      REDMINE_DB_PASSWORD: ${MYSQL_PASSWORD:-redmine}
      REDMINE_SECRET_KEY_BASE: ${REDMINE_SECRET_KEY_BASE}
    volumes:
      - redmine_files:/usr/src/redmine/files
      - ./plugins:/usr/src/redmine/plugins-source:ro
      - ./init-plugins.sh:/usr/src/redmine/init-plugins.sh:ro
    command: ["sh", "-c", "/usr/src/redmine/init-plugins.sh && bundle exec rails server -b 0.0.0.0"]

volumes:
  db_data:
  redmine_files: