name: Build and Test Redmine Container

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t redmine-monorepo .
    
    - name: Start services
      run: |
        docker-compose up -d
    
    - name: Wait for services to be ready
      run: |
        echo "Waiting for database to be ready..."
        sleep 30
        
        echo "Waiting for Redmine to be ready..."
        timeout 300 bash -c 'until curl -f http://localhost:3000; do sleep 5; done'
    
    - name: Test Redmine accessibility
      run: |
        curl -f http://localhost:3000 || exit 1
        echo "Redmine is accessible!"
    
    - name: Check logs
      if: failure()
      run: |
        echo "=== Docker Compose Services ==="
        docker-compose ps
        echo "=== Redmine Logs ==="
        docker-compose logs redmine
        echo "=== Database Logs ==="
        docker-compose logs db
    
    - name: Cleanup
      if: always()
      run: |
        docker-compose down -v